exports.states = {

  'PIN' : {
    title : 'Sisesta PIN',
    b1: { title:null, go: null },
    b2: { title:null, go: null },
    b3: { title:null, go: null },
    b4: { title:'****', go: 'Esileht' },
  },
  'Esileht' : {
    title : 'Tere tulemast',
    b1: { title:'Keel', go: 'Keel' },
    b2: { title:'Kaardi tagastamine', go: 'Lõpp' },
    b3: { title:'Sularaha', go: 'Sularaha' },
    b4: { title:'Kontojääk', go: 'Kontojääk' },  
  },
  'Keel' : {
    title : '...',
    b1: { title:'Eesti', go: 'Esileht' },
    b2: { title:'English', go: 'Esileht' },
    b3: { title:'Pусский', go: 'Esileht' },
    b4: { title:'Suomi', go: 'Esileht' },  
  },
  'Sularaha' : {
    title : 'Palun vali summa',
    b1: { title: '5 EUR', go: 'Raha kättesaamine' },
    b2: { title:'20 EUR', go: 'Raha kättesaamine' },
    b3: { title:'50 EUR', go: 'Raha kättesaamine' },
    b4: { title:'Muu summa', go: 'Muu' },  
  },
  'Kontojääk' : {
    title: 'Kontojääk',
    b1: { title: null, go: null },
    b2: { title:'Katkesta', go: 'Esileht' },
    b3: { title:'Paberil', go: 'Paberil' },
    b4: { title:'Ekraanil', go: 'Ekraanil' },  
  },
  'Raha kättesaamine' : {
    title: 'Palun oodake, raha väljastatakse',
    timer: {time: 3000, go: 'Esileht'},
    b1: { title: null, go: null },
    b2: { title: null, go: null },
    b3: { title: null, go: null},
    b4: { title: null, go: null },  
  },  
  'Ekraanil' : {
    title: 'Vabad vahendid:5000 EUR',
    b1: { title: null, go: null },
    b2: { title:'Katkesta', go: 'Esileht' },
    b3: { title: null, go: null},
    b4: { title: null, go: null },  
  },
  'Paberil' : {
    title: 'Oodake, kviitungit väljastatakse',
    b1: { title: null, go: null },
    b2: { title:'Katkesta', go: 'Esileht' },
    b3: { title: null, go: null},
    b4: { title: null, go: null },  
  },
  'Muu' : {
    title: '[..................]',
    b1: { title: null, go: null },
    b2: { title:'Katkesta', go: 'Esileht' },
    b3: { title: null , go: null},
    b4: { title: 'Sisesta', go: 'Raha kättesaamine' },  
  },
  'Lõpp' : {
    title : 'Palun võtke kaart',
    timer: {time: 3000, go: 'PIN'},
    b1: { title:null, go: null },
    b2: { title:null, go: null },
    b3: { title:null, go:null },
    b4: { title:null, go: null },  
  },
}